title: David Chen's Personal Site
email: davidc3287@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple website for presenting independent study and various personal projects, as well as possible blog posts.
github_username: dchen327

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
plugins:
  - jekyll-include-cache
